version: "3.0"

services:

  library:
    depends_on:
      - db
    ports:
      - 4000:4004
    expose:
      - "4004"
    build: ./
    environment:
      DB_URL: postgresql://user:password@db:5432/privatestore
    tty: true

  db:
    image: postgres:13.7-bullseye
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: privatestore
    volumes:
      - db-data:/db-data/

volumes:
  db-data:
