version: "3"

services:
  repoint-opreturn:
    image: repoint_opreturn:0.1.0
    volumes:
      - ../:/project
      - repoint-opreturn-node-modules-data-volume:/usr/local/node_modules
    tty: true

volumes:
  repoint-opreturn-node-modules-data-volume:
    external: true